// Number-clip manifest + WebAudio composition for the /tal dictation drill.
// Numbers play from committed human clips composed atom-by-atom — NEVER TTS
// (product invariant; no fallback here, unlike speech.ts for words). The pure
// half (planClips/levelAvailable/atomsForLevel) is unit-tested; the player
// half is WebAudio DOM code, covered by the manual pass (repo policy).
//
// Manifest contract: src/data/number-audio.json (generated by the TTS
// script's reconcile step in a later phase) lists EVERY atom in NUMBER_ATOMS
// keyed by word, with id = lessonAudioId(word) and `present` reflecting the
// clip on disk — it doubles as the user's recording checklist.

import {
  numberToTokens,
  priceToTokens,
  yearToTokens,
  type NumberLevelId,
} from './danish-numbers.ts';
import { withBase } from './url.ts';

export type NumberAudioManifest = {
  atoms: Record<string, { id: string; file: string; present: boolean }>;
};

/** Clip ids to play, in order, for a token sequence — or null if ANY atom is
 *  unlisted or not yet recorded (callers must then disable playback, not
 *  degrade to TTS). */
export function planClips(tokens: string[], m: NumberAudioManifest): string[] | null {
  const ids: string[] = [];
  for (const token of tokens) {
    const atom = m.atoms[token];
    if (!atom || !atom.present) return null;
    ids.push(atom.id);
  }
  return ids;
}

/** Every atom the level's generator can emit, first-seen order, deduped.
 *  The ranges MIRROR the NUMBER_LEVELS gens in danish-numbers.ts (0–20 ·
 *  whole tens 20–90 · 0–99 · numbers 100–999 / years 1900–2099 / prices
 *  1–999 kroner) — the gen-sweep test in number-audio.test.ts guards the sync. */
export function atomsForLevel(level: NumberLevelId): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  const add = (tokens: string[]): void => {
    for (const t of tokens) {
      if (!seen.has(t)) {
        seen.add(t);
        out.push(t);
      }
    }
  };
  switch (level) {
    case '0-20':
      for (let n = 0; n <= 20; n++) add(numberToTokens(n));
      break;
    case 'tiotal':
      for (let n = 20; n <= 90; n += 10) add(numberToTokens(n));
      break;
    case '0-99':
      for (let n = 0; n <= 99; n++) add(numberToTokens(n));
      break;
    case 'stora-tal':
      for (let n = 100; n <= 999; n++) add(numberToTokens(n));
      for (let y = 1900; y <= 2099; y++) add(yearToTokens(y));
      for (let kr = 1; kr <= 999; kr++) add(priceToTokens(kr));
      break;
  }
  return out;
}

/** A level is offered only when every clip it could need exists — partial
 *  coverage would make random prompts silently unplayable mid-session. */
export function levelAvailable(level: NumberLevelId, m: NumberAudioManifest): boolean {
  return atomsForLevel(level).every((word) => m.atoms[word]?.present === true);
}

export type NumberPlayOutcome = 'played' | 'blocked' | 'cancelled' | 'missing';

export interface NumberAudioPlayer {
  canPlay(tokens: string[]): boolean;
  /** Warm the decode cache (the drill preloads the next prompt). Best-effort,
   *  never throws. */
  preload(tokens: string[]): Promise<void>;
  /** Resolves at playback START (like speech.ts speak()); 'blocked' = no user
   *  gesture yet — caller shows a ▶ Spela button. */
  play(tokens: string[], opts?: { gapMs?: number }): Promise<NumberPlayOutcome>;
  stop(): void;
}

// ---------------------------------------------------------------------------
// Impure WebAudio half — module-level state so ALL players share one context,
// one decode cache and one no-overlap sequence.

// Lazy shared AudioContext, SSR-safe. NOTE: a later phase may extract this
// into src/lib/webaudio.ts as getAudioContext(); keep the semantics identical.
let sharedCtx: AudioContext | null | undefined; // undefined = not yet attempted

function getContext(): AudioContext | null {
  if (sharedCtx !== undefined) return sharedCtx;
  sharedCtx = null;
  if (typeof window !== 'undefined') {
    const w = window as Window & { webkitAudioContext?: typeof AudioContext };
    const Ctor = window.AudioContext ?? w.webkitAudioContext;
    if (Ctor) {
      try {
        sharedCtx = new Ctor();
      } catch {
        /* stays null — play() reports 'blocked' */
      }
    }
  }
  return sharedCtx;
}

// Decoded-buffer cache keyed by clip id. Promises are cached (not buffers) so
// concurrent preload+play of the same atom fetch/decode only once.
const bufferCache = new Map<string, Promise<AudioBuffer>>();

function loadBuffer(ctx: AudioContext, id: string): Promise<AudioBuffer> {
  const hit = bufferCache.get(id);
  if (hit) return hit;
  const p = (async () => {
    const res = await fetch(withBase('audio/' + id + '.mp3'));
    if (!res.ok) throw new Error(`number clip fetch failed (${res.status}): ${id}`);
    return ctx.decodeAudioData(await res.arrayBuffer());
  })();
  // Evict failures so a flaky fetch is retried on the next play.
  p.catch(() => bufferCache.delete(id));
  bufferCache.set(id, p);
  return p;
}

// Monotonic call id, mirroring speech.ts speakSeq: a newer play()/stop()
// supersedes any play() still awaiting buffers, so sequences never overlap.
let playSeq = 0;
const activeSources = new Set<AudioBufferSourceNode>();

function stopSources(): void {
  for (const src of activeSources) {
    try {
      src.stop();
    } catch {
      /* already ended */
    }
  }
  activeSources.clear();
}

const DEFAULT_GAP_MS = 100;

export function createNumberAudioPlayer(m: NumberAudioManifest): NumberAudioPlayer {
  return {
    canPlay: (tokens) => planClips(tokens, m) !== null,

    async preload(tokens) {
      const ids = planClips(tokens, m);
      const ctx = getContext();
      if (!ids || !ctx) return;
      await Promise.all(ids.map((id) => loadBuffer(ctx, id).catch(() => undefined)));
    },

    async play(tokens, opts = {}) {
      const ids = planClips(tokens, m);
      if (!ids) return 'missing';
      const seq = ++playSeq;
      stopSources();
      const ctx = getContext();
      if (!ctx) return 'blocked';
      let buffers: AudioBuffer[];
      try {
        buffers = await Promise.all(ids.map((id) => loadBuffer(ctx, id)));
      } catch {
        // A clip listed as present failed to load — treat as missing audio,
        // never fall back to TTS.
        return seq === playSeq ? 'missing' : 'cancelled';
      }
      if (seq !== playSeq) return 'cancelled';
      if (ctx.state === 'suspended') {
        try {
          await ctx.resume();
        } catch {
          return 'blocked';
        }
        if (seq !== playSeq) return 'cancelled';
      }
      if (ctx.state !== 'running') return 'blocked'; // autoplay policy: needs a user gesture
      const gap = (opts.gapMs ?? DEFAULT_GAP_MS) / 1000;
      let t = ctx.currentTime + 0.03; // small lead so the first start() isn't in the past
      for (const buf of buffers) {
        const src = ctx.createBufferSource();
        src.buffer = buf;
        src.connect(ctx.destination);
        src.onended = () => activeSources.delete(src);
        activeSources.add(src);
        src.start(t);
        t += buf.duration + gap;
      }
      return 'played';
    },

    stop() {
      playSeq++; // cancels any play() still awaiting buffers
      stopSources();
    },
  };
}
