import { describe, it, expect } from 'vitest';
import { waveformSpec, waveformSpecFromHeights, VIEW_H, type WaveformSize, type RealWaveform } from './waveform.ts';
import heroWaveform from '../data/hero-waveform.json';

const EXPECTED: { size: WaveformSize; count: number; gapLength: number }[] = [
  { size: 'icon', count: 12, gapLength: 2 },
  { size: 'hero', count: 24, gapLength: 3 },
  { size: 'divider', count: 36, gapLength: 3 },
];

describe('waveformSpec', () => {
  it('emits the expected bar count per size', () => {
    for (const { size, count } of EXPECTED) {
      expect(waveformSpec(size).bars).toHaveLength(count);
    }
  });

  it('marks exactly gapLength gap bars, contiguous and centered', () => {
    for (const { size, count, gapLength } of EXPECTED) {
      const spec = waveformSpec(size);
      const gapIdx = spec.bars.flatMap((b, i) => (b.gap ? [i] : []));
      expect(gapIdx).toHaveLength(gapLength);
      expect(spec.gapLength).toBe(gapLength);
      // contiguous run starting at gapStart
      for (let k = 0; k < gapIdx.length; k += 1) {
        expect(gapIdx[k]).toBe(spec.gapStart + k);
      }
      // centered: midpoint of the gap within one bar of the waveform midpoint
      const mid = spec.gapStart + gapLength / 2;
      expect(Math.abs(mid - count / 2)).toBeLessThanOrEqual(1);
    }
  });

  it('keeps every gap bar shorter than every non-gap bar', () => {
    for (const { size } of EXPECTED) {
      const spec = waveformSpec(size);
      const gapMax = Math.max(...spec.bars.filter((b) => b.gap).map((b) => b.height));
      const mainMin = Math.min(...spec.bars.filter((b) => !b.gap).map((b) => b.height));
      expect(gapMax).toBeLessThan(mainMin);
    }
  });

  it('is deterministic', () => {
    expect(waveformSpec('hero')).toEqual(waveformSpec('hero'));
  });

  it('places bars at uniform pitch and inside the width', () => {
    for (const { size } of EXPECTED) {
      const spec = waveformSpec(size);
      const first = spec.bars[0];
      const second = spec.bars[1];
      expect(first?.x).toBe(0);
      const pitch = (second?.x ?? 0) - (first?.x ?? 0);
      spec.bars.forEach((b, i) => {
        expect(b.x).toBeCloseTo(i * pitch, 10);
        expect(b.x + spec.barWidth).toBeLessThanOrEqual(spec.width);
      });
    }
  });

  it('leaves pulse headroom: height * 1.6 never exceeds the viewBox', () => {
    for (const { size } of EXPECTED) {
      for (const bar of waveformSpec(size).bars) {
        expect(bar.height * 1.6).toBeLessThanOrEqual(VIEW_H);
        // center-anchored
        expect(bar.y).toBeCloseTo((VIEW_H - bar.height) / 2, 10);
      }
    }
  });

  it('viewBox string matches width and height', () => {
    for (const { size } of EXPECTED) {
      const spec = waveformSpec(size);
      expect(spec.height).toBe(VIEW_H);
      expect(spec.viewBox).toBe(`0 0 ${spec.width} ${spec.height}`);
    }
  });
});

describe('waveformSpecFromHeights', () => {
  const real: RealWaveform = { heights: [0.1, 0.5, 0.95, 0.7, 0.2, 0.4, 0.3, 0.1], dip: [4, 2] };

  it('emits one bar per height at uniform pitch inside the width', () => {
    const spec = waveformSpecFromHeights(real);
    expect(spec.bars).toHaveLength(real.heights.length);
    const pitch = (spec.bars[1]?.x ?? 0) - (spec.bars[0]?.x ?? 0);
    spec.bars.forEach((b, i) => {
      expect(b.x).toBeCloseTo(i * pitch, 10);
      expect(b.x + spec.barWidth).toBeLessThanOrEqual(spec.width);
    });
    expect(spec.viewBox).toBe(`0 0 ${spec.width} ${spec.height}`);
  });

  it('marks exactly the dip bars as gap, none without a dip', () => {
    const spec = waveformSpecFromHeights(real);
    expect(spec.bars.map((b) => b.gap)).toEqual([false, false, false, false, true, true, false, false]);
    const noDip = waveformSpecFromHeights({ heights: real.heights });
    expect(noDip.bars.every((b) => !b.gap)).toBe(true);
  });

  it('clamps out-of-range heights and keeps pulse headroom + centering', () => {
    const spec = waveformSpecFromHeights({ heights: [0, -1, 2, 0.5] });
    for (const bar of spec.bars) {
      expect(bar.height * 1.6).toBeLessThanOrEqual(VIEW_H);
      expect(bar.height).toBeGreaterThan(0);
      expect(bar.y).toBeCloseTo((VIEW_H - bar.height) / 2, 10);
    }
  });

  it('is deterministic', () => {
    expect(waveformSpecFromHeights(real)).toEqual(waveformSpecFromHeights(real));
  });
});

// Drift guard for the COMMITTED manifest (regenerated by scripts/waveform-data.ts):
// a bad regeneration should fail tests, not ship a broken hero.
describe('hero-waveform.json manifest', () => {
  it('has both hero words with sane bar data', () => {
    for (const word of ['hun', 'hund'] as const) {
      const entry = heroWaveform[word];
      expect(entry, word).toBeDefined();
      expect(entry.heights.length).toBeGreaterThanOrEqual(4);
      expect(entry.heights.length).toBeLessThanOrEqual(16);
      for (const h of entry.heights) {
        expect(h).toBeGreaterThanOrEqual(0.05);
        expect(h).toBeLessThanOrEqual(0.95);
      }
    }
  });

  it('hund carries an interior stød dip', () => {
    const { heights, dip } = heroWaveform.hund;
    expect(dip).toBeDefined();
    const [start = -1, len = 0] = dip;
    expect(len).toBeGreaterThanOrEqual(1);
    expect(len).toBeLessThanOrEqual(3);
    expect(start).toBeGreaterThan(0);
    expect(start + len).toBeLessThan(heights.length);
  });
});
